### ISSUE TITLE
(Question) Freeing components

### ISSUE THREAD

**Issue by mtn** [marcusva/py-sdl2#107]
Not a bug this time, but I had a question about using the library that I couldn't find an answer to in the documentation. In my application, I have some surfaces/textures that I finish using at some point. I get rid of references to the things themselves (the variables I bound when creating them), but they continue to be rendered and I can see them in the growing components list. For example, I'll create a rectangle like so:

```
rect = Rect(world,factory.from_color(WHITE,size=(600,10)),0,0)
```

much like you demonstrated in one of the tutorials. I think the relevant thing I need to make sure if properly destroyed is the texture/surface that's created by `factory...` so it stops being rendered when I no longer want it. How can I do this? Thanks in advance!

**Comment by marcusva** [comment]
Assuming that `rect` is an `Entity` being added to your `world`, simply call  `world.delete(the_rect_to_remove)` to remove it from the component list.

**Comment by mtn** [comment]
Thanks so much!
