### ISSUE TITLE
(Question) Packaging applications

### ISSUE THREAD

**Issue by mtn** [marcusva/py-sdl2#108]
Sorry for the rapidfire questions! I think this will be the last one. I'm not totally familiar with python, and am curious about how I might go about packaging up a program that I wrote that relies upon this library to others. I think it might be easier if all the packages in the project are on pip, but not sure. Thanks in advance!

**Comment by marcusva** [comment]
It depends on your approach of shipping the application. distutils (or setuptools) and PyPi are the standard way of creating distributable packages and making them available to others. Those however require target users to know about Python, PyPi and so on.

If you aim to ship a ready-to-run application to users, PyInstaller or py2app might be suitable (see https://wiki.python.org/moin/DistributionUtilities for additional resources). My knowledge about those however is limited to whatever shows up in your favourite web search ;-).

**Comment by mtn** [comment]
Great, thanks for the response!
