### ISSUE TITLE
sdl2.SDL_WINDOWEVENT_SIZE_CHANGED seems to also respond when mouse enter or exit window 

### ISSUE THREAD

**Issue by sunbearc22** [marcusva/py-sdl2#109]
Hi. I noticed the above issue. My thought is that if there is no window size change event, print out of the window size should not appear. Is there a bug here? [My test script.](https://discourse.libsdl.org/t/sdl-windowevent-sdl-windowevent-size-changed-sdl-windowevent-resized-not-responding/23261/13?u=sunbear)

**Comment by marcusva** [comment]
I assume, that you refer to the following main loop excerpt:
```python
# Poll for currently pending events.
while sdl2.SDL_PollEvent(ctypes.byref(event)) != 0:        

if event.type == sdl2.SDL_QUIT:
    print('SDL2 Main Loop: sdl2.SDL_QUIT.')
    running = False
    break

    if event.type == sdl2.SDL_WINDOWEVENT:
        if sdl2.SDL_WINDOWEVENT_SIZE_CHANGED:
             print('SDL_WINDOWEVENT_SIZE_CHANGED: windowID {0}:'
                 ' [{1} {2}]'.format( event.window.windowID,
                     event.window.data1,
                     event.window.data2))
```

The issue is within `if sdl2.SDL_WINDOWEVENT_SIZE_CHANGED:`, which you want to be
`if event.window.event == sdl2.SDL_WINDOWEVENT_SIZE_CHANGED:` to have a correct behaviour.

**Comment by sunbearc22** [comment]
Thanks you!
