### ISSUE TITLE
No way to close a window via sdl2.ext besides completely exiting SDL2 (!)

### ISSUE THREAD

**Issue by sfsdfd** [marcusva/py-sdl2#111]
py-sdl2.ext currently lacks any way to close a window.

The functionality is just not there in .ext. There's a hidden __del__ function, but that is apparently intended to be internal.

Also, trying to SDL_DestroyWindow(window) produces an error, since that function does not expect an instance of sdl2.ext.Window, but rather POINTER(SDL_Window), and I don't know how to get a pointer to an object in Python.

As a result, the only way to close a window in SDL2 - *any* window - is to call sdl2.ext.exit() and shut down the entire SDL library. That is... not good.

**Comment by marcusva** [comment]
You are correct. A close() and open() function should be made available to close and (re)open windows.

**Comment by marcusva** [comment]
This has been fixed in commit 27a4aac
