### ISSUE TITLE
sdl2.ext window positions are arbitrary, and windows cannot be moved

### ISSUE THREAD

**Issue by sfsdfd** [marcusva/py-sdl2#112]
sdl2.ext only has one way to set the position of a window: specifying POS while creating the window.

First, there is no way to move a window through sdl2.ext. No function provides that functionality.

Second, POS is occasionally ignored while creating the window anyway. Sometimes it works; sometimes it chooses arbitrary coordinates. Trying to create two windows at the same coordinate (0,0) sometimes results in one correctly positioned and one haphazardly put elsewhere.

**Comment by marcusva** [comment]
SDL2 offers ways to set the position of a window at runtime. Those are not exposed (yet) as property on the sdl2.ext.Window class. I'll add this as a TODO for the next update.

You can work around that behaviour by using the sdl2.SDL_SetWindowPosition() function on the sdl2.ext.Window:

```python
yourwindow = sdl2.ext.Window(....)
sdl2.SDL_SetWindowPosition(yourwindow.window, 100, 100)
```

Please note that setting the position of a window is a hint and may be ignored, depending on your underlying OS and window manager.

**Comment by ali1234** [comment]
Can window.size property also get a setter please?
