### ISSUE TITLE
sdl2 is fundamentally incompatible with Tkinter

### ISSUE THREAD

**Issue by sfsdfd** [marcusva/py-sdl2#114]
sdl2 and Tkinter cannot coexist. At least, not in Python.

The reason they cannot coexist is that both libraries expect to run on the primary thread. Both libraries throw up fatal errors if not running on the primary thread, including bizarre, uncatchable segmentation faults when trying to open a window, and arbitrary, unhelpful error messages like "message queue not in the main thread."

Neither sdl2 nor Tkinter makes this requirement particularly clear up front. But because they both have an absolute requirement of running on the primary thread, it is impossible to combine them in one project.

**Comment by marcusva** [comment]
SDL2's video functions and event handling system are bound to whatever the underlying system provides or what is configured. The majority of them are not thread-safe or not able to be executed properly in a multi-threaded environment without running in the main-thread.

https://wiki.libsdl.org/FAQDevelopment and various discussions on the SDL mailing list contain more details.
