### ISSUE TITLE
rwops.py's write method returns wrong value

### ISSUE THREAD

**Issue by StoddardOXC** [marcusva/py-sdl2#126]
rwops.py's write() method returns bytes written instead of units written. This breaks anything that checks SDL_RWwrite()'s return value. 

Interestingly, the read() method returns correct values. Please fix, the fix is trivial - do it the same way it's done in read()

**Comment by StoddardOXC** [comment]
The simplest fix is:

```diff
diff --git a/sdl2/rwops.py b/sdl2/rwops.py
index a542e7a..2eb9fa1 100644
--- a/sdl2/rwops.py
+++ b/sdl2/rwops.py
@@ -192,7 +192,7 @@ def rw_from_object(obj):
             if retval is None:
                 # No return value; we assume that everything is okay.
                 return num
-            return retval
+            return retval // size
         except Exception:
             #print(e)
             return 0
```

But the ``# No return value; we assume that everything is okay.`` bit is incorrect under Python 3, because there the file object's .write() method's return value of None actually means something like `EAGAIN` / `EWOULDBLOCK`. (see io.RawIOBase docs in [https://docs.python.org/3.7/library/io.html#module-io](https://docs.python.org/3.7/library/io.html#module-io))

So the better patch would be:

```diff
diff --git a/sdl2/rwops.py b/sdl2/rwops.py
index a542e7a..2179708 100644
--- a/sdl2/rwops.py
+++ b/sdl2/rwops.py
@@ -190,9 +190,11 @@ def rw_from_object(obj):
             # string_at feels wrong, since we access a raw byte buffer...
             retval = obj.write(string_at(ptr, size * num))
             if retval is None:
-                # No return value; we assume that everything is okay.
-                return num
-            return retval
+                if sys.hexversion > 0x3000000
+                    return 0
+                else:
+                    return num
+            return retval // size
         except Exception:
             #print(e)
             return 0
```

**Comment by a-hurst** [comment]
Hopefully fixed in [the latest commit](https://github.com/marcusva/py-sdl2/commit/d1d50b0caa9d5aa217b6a467f796919ba4ef5334), thanks so much for reporting this! Instead of just checking the Python version I made it check for the object class being a subclass of io.IOBase, since the write() method of IOBytes objects in 2.7 also returns number of bytes written on success and None on failure. When I have time I should probably write a proper test for this in the testing suite.

Thanks again!
