### ISSUE TITLE
sdl2.SDL_Free is missing, needed for sdl2.SDL_GetClipboardText()

### ISSUE THREAD

**Issue by JonasT** [marcusva/py-sdl2#128]
sdl2.SDL_Free is missing, which is required to use sdl2.SDL_GetClipboardText() without memory leaks. I know it's just an alias to `free()` but ctypes in its infinite wisdom seems to assume I don't need that, so there's no easy way to get it. Therefore, I suggest `PySDL2` should take care of this and provide it as `sdl2.SDL_Free`, so it matches the expectations from the documentation.

**Comment by JonasT** [comment]
Nice, and `libc.free()` crashes right away (segmentation fault). So I'm wondering how the clipboard API can even be used?

This is my current attempt which crashes after the first print: (libc being `CDLL(find_library("c"))`)
```
        paste_text_ptr = ctypes.c_char_p()
        old_restype = sdl.SDL_GetClipboardText.restype
        sdl.SDL_GetClipboardText.restype = ctypes.c_void_p
        paste_text_ptr = sdl.SDL_GetClipboardText()
        sdl.SDL_GetClipboardText.restype = old_restype
        if paste_text_ptr == 0:
            return
        paste_text = ctypes.cast(paste_text_ptr, ctypes.c_char_p).\
            value.decode("utf-8", "replace")
        print("FREEING...", flush=True)
        libc.free(paste_text_ptr)
        print("FREE DONE", flush=True)
```

**Comment by marcusva** [comment]
``SDL_free()`` is mapped properly within the sdl2 namespace: https://github.com/marcusva/py-sdl2/blob/master/sdl2/stdinc.py#L28

Also, ``SDL_free()`` is not necessarily a wrapper around libc's ``free()`` function. It may vary, depending on the SDL2 build and could even use SDL2's own memory allocator, which is incompatible to ``free()``, so you should not use ``free()`` for buffers allocated through SDL2 (if not stated otherwise).

As for retrieving the clipboard content, you can try the following:

    content= sdl2.SDL_GetClipboardText()
    if content:
        text = content.value.decode("utf-8", "replace")
        sdl2.SDL_free(content) # unchecked, content may need a cast to c_void_p
    else:
        # Nothing in clipboard

**Comment by JonasT** [comment]
Ah right. How silly of me to name it wrong! Your code doesn't work by the way, because `content` will be immediately provided as Python string (`content.value` doesn't exist):

```
$ python3
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdl2
>>> sdl2.SDL_GetClipboardText()
b''
>>> sdl2.SDL_GetClipboardText().value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bytes' object has no attribute 'value'
>>>
```
**To anyone stumbling across here, this clipboard code works:**
```python
def get_clipboard_text():
    paste_text_ptr = ctypes.c_char_p()
    old_restype = sdl.SDL_GetClipboardText.restype
    sdl.SDL_GetClipboardText.restype = ctypes.c_void_p
    paste_text_ptr = sdl.SDL_GetClipboardText()
    sdl.SDL_GetClipboardText.restype = old_restype
    if paste_text_ptr == 0:
        return
    paste_text = ctypes.cast(paste_text_ptr, ctypes.c_char_p).\
        value.decode("utf-8", "replace")
    sdl.SDL_free(paste_text_ptr)
    return paste_text
```
