### ISSUE TITLE
pixels2d doesn't work with PyPy

### ISSUE THREAD

**Issue by stillinbeta** [marcusva/py-sdl2#132]
I'm trying to get direct pixel access working on PyPy, but I'm running into some weird errors around the buffer interface. 
```python
import sdl2
import sdl2.ext

if __name__ == "__main__":
    window = sdl2.ext.Window("PyBoy", size=(800,600))
    surface = window.get_surface()

    pixels2d = sdl2.ext.pixels2d(surface)
```

On both python2 and python3 this produces errors:

python2.7 (pypy 6.0)
```
(pypy2) $ python testsdl.py
testsdl.py:8: ExperimentalWarning: 'pixels2d' is in an experimental state.
  pixels2d = sdl2.ext.pixels2d(surface)
Traceback (most recent call last):
  File "testsdl.py", line 8, in <module>
    pixels2d = sdl2.ext.pixels2d(surface)
  File "/tmp/pypy2/site-packages/sdl2/ext/compat.py", line 102, in wrapper
    return func(*fargs, **kw)
  File "/tmp/pypy2/site-packages/sdl2/ext/pixelaccess.py", line 153, in pixels2d
    psurface).transpose()
  File "/tmp/pypy2/site-packages/sdl2/ext/pixelaccess.py", line 103, in __new__
    offset, strides, order)
TypeError: expected a readable buffer object
zsh: exit 1     python testsdl.py
```

python3.5 (pypy 6.0):
```
testsdl.py:8: ExperimentalWarning: 'pixels2d' is in an experimental state.
  pixels2d = sdl2.ext.pixels2d(surface)
Traceback (most recent call last):
  File "testsdl.py", line 8, in <module>
    pixels2d = sdl2.ext.pixels2d(surface)
  File "/home/liz/ppp/server/venv/site-packages/sdl2/ext/compat.py", line 102, in wrapper
    return func(*fargs, **kw)
  File "/home/liz/ppp/server/venv/site-packages/sdl2/ext/pixelaccess.py", line 153, in pixels2d
    psurface).transpose()
  File "/home/liz/ppp/server/venv/site-packages/sdl2/ext/pixelaccess.py", line 103, in __new__
    offset, strides, order)
TypeError: 'c_ubyte_Array_1920000' does not have the buffer interface
zsh: exit 1     python testsdl.py
```

In both cases I'm using `pysdl==0.9.6` and `numpy==0.15.4` (0.16.0 is broken on PyPy right now)

**Comment by stillinbeta** [comment]
looks like this is a known issue as per 48fbb163e3dcc3dd0091dd61ebeefc1c2d78a844

**Comment by stillinbeta** [comment]
https://bitbucket.org/pypy/pypy/commits/36aba877dfa1/ makes it sound like the referenced issue is fixed. I'm going to re-enable the tests in a PR and see what it does to the build matrix.

**Comment by stillinbeta** [comment]
@Baekalfen is this why PyBoy uses numpypy?

**Comment by stillinbeta** [comment]
#133 looks like it passes, though the pixels2d tests are still "unimplemented," so no real signal there

**Comment by Baekalfen** [comment]
Have you followed the instructions in the readme from PyBoy, and does PyBoy work? If it does, then you should try to figure out the difference here. I don't recognise this error message.

**Comment by Baekalfen** [comment]
On my system, macOS Mojave, PyBoy works fine, so direct pixel access must as well.

I'm using the following versions:

    $ pypy
    Python 2.7.13 (ab0b9caf307db6592905a80b8faffd69b39005b8, Jun 24 2018, 08:19:27)
    [PyPy 6.0.0 with GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>>> import numpy
    >>>> numpy.__version__
    '1.10.0'
    >>>> import sdl2
    >>>> sdl2.__version__
    '0.9.6'
    >>>>

**Comment by stillinbeta** [comment]
@Baekalfen numpy `1.10.0` makes it look like you're using numpypy, not numpy (https://bitbucket.org/pypy/numpy/src/4f9778cd49a48096f97cf85116b8820f3da6f80a/setup.py?at=master&fileviewer=file-view-default#setup.py-80)

I know PyBoy works with numpypy, but that project's mostly been abandoned and doesn't support python3, so I'm trying to see if I can get upstream numpy to work as well.

**Comment by Baekalfen** [comment]
I don't know the exact status of NumPy vs NumPyPy, but back when I started PyBoy, I remember, that NumPy just fundamentally didn't work on PyPy. I think it was related to how each Python implementation interfaces with C-code.

**Comment by mattip** [comment]
While `pip install numpy` should just work these days on PyPy, we still have an open issue on [interaction with ctypes](https://bitbucket.org/pypy/pypy/issues/2930). The line below that is failing, together with `c_ubyte_Array_1920000` in the error message, lead me to believe you are hitting this corner. We hope to fix this soon.
```
sfarray = numpy.ndarray.__new__(cls, shape, dtype, buffer_,
                                            offset, strides, order)
```

**Comment by a-hurst** [comment]
Unless I'm misreading things, it looks like the only things left to do on our end are:

1. Update pixels2d and pixels3d to be less "experimental" (I already have most of the code to do this from one of my own projects)
2. Add better/more thorough testing of those functions so that we can tell whether they're working correctly in PyPy via CI

I can hopefully get around to both of these before the 0.9.7 release in a few weeks.

**Comment by a-hurst** [comment]
Okay, tests for pixels2d and pixels3d have been fully written/rewritten as of the latest commit, and are tested and working on PyPy via Travis CI! 

I also added a new 'transpose' flag to both functions since traditionally the numpy array view returned by them shows up as mirrored/rotated when passed to PIL or PyOpenGL. Now if you add the `transpose=False` flag, they'll work properly with those libraries.
