### ISSUE TITLE
documentation for sdl2gfx points to wrong page

### ISSUE THREAD

**Issue by erose1337** [marcusva/py-sdl2#141]
The [documentation for sdl2.sdlgfx](https://pysdl2.readthedocs.io/en/latest/modules/sdl2_sdlgfx.html?highlight=gfx#module-sdl2.sdlgfx) says that it is a wrapper around SDL2_GFX. 

The link at the end of that documentation page points to http://www.ferzkopp.net/Software/SDL_gfx-2.0/ , which is the documentation for SDL_gfx-2.0. This is the 2.0 version of the SDL_gfx library. SDL2_gfx (note the placement of the 2) is a different library, and the documentation to it is located here: http://www.ferzkopp.net/Software/SDL2_gfx/Docs/html/index.html.

**Comment by a-hurst** [comment]
Fixed in the latest commit. Thanks for the bug report!
