### ISSUE TITLE
SDL_mixer 2.0.4: `Mix_HasMusicDecoder` is not defined

### ISSUE THREAD

**Issue by zmarvel** [marcusva/py-sdl2#143]
## Steps to reproduce

```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdl2.sdlmixer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zack/src/py-sdl2/sdl2/sdlmixer.py", line 149, in <module>
    Mix_HasMusicDecoder = _bind("Mix_HasMusicDecoder", [c_char_p], SDL_bool)
  File "/home/zack/src/py-sdl2/sdl2/dll.py", line 87, in bind_function
    (funcname, self._dll))
ValueError: could not find function 'Mix_HasMusicDecoder' in <CDLL 'libSDL2_mixer-2.0.so.0', handle 1379920 at 0x7f66130b2b00>
```

## Description

This symbol is declared `extern` in `SDL_mixer.h` as of the 2.0.3 release, but is not defined anywhere (I believe this is a bug in SDL_mixer).

After removing the line in `sdlmixer.py` that requires this symbol, I am able to import the `sdl2.sdlmixer` module.

**Comment by a-hurst** [comment]
I've fixed this bug as part of my pull request here: https://github.com/marcusva/py-sdl2/pull/138, so we're just waiting around on the maintainer to take a look and merge. Maybe someone should send @marcusva an email or something asking if they're still maintaining the project, and if not create an official fork to pick up where they left off.
