### ISSUE TITLE
New PyPi release (0.9.7)?

### ISSUE THREAD

**Issue by a-hurst** [marcusva/py-sdl2#150]
It's been over 2 years since the last PyPi release of pysdl2, and there are a few important bugfixes that have been added to the GitHub version since the last one (importantly for me, the patches that allow [pysdl2-dll](https://github.com/a-hurst/pysdl2-dll) to work on macOS). As such, I figure it's worth discussing what (if anything) should be done/fixed before the next PyPi version of pysdl2 is released. Off the top of my head, here are a few odds and ends:

- Syncing the package with the latest SDL2 2.0.10 changes (looking at the changelog, I don't think there's much needed here)
- Fixing Appveyor/Travis CI so it's passing again (I'm willing to tackle the bulk of this, pysdl2-dll should simplify the pipeline quite a bit for macOS and Windows)
- Adding official support for pysdl2-dll (essentially just adding a "try: import sdl2dll, except ImportError: pass" to the top of dll.py, so you don't need to add sdl2dll to your scripts to be able to use it).
- Closing some of the remaining open issues that seem easy and important.

Re: pysdl2-dll support, I've got everything working so that it's generating pip-installable wheels with the full suite of relevant macOS/Win32/Win64 SDL2 binaries included, and am getting it onto PyPi shortly, so we should finally be able to close #78!

Also @marcusva since I don't have access to the PyPi repository, you'll have to upload the new release when you find time. What do you think is needed before a 0.9.7 can/should be released?

EDIT: Okay, here's a checklist of what should get done before the next release:

*For sure*:
- [x] Fix failing Linux tests on TravisCI
- [x] Fix failing macOS tests on TravisCI
- [x] Fix failing Windows tests on Appveyor
- [x] Sync with SDL2 2.0.10 headers
- [x] Sync with SDL2_mixer 2.0.4 headers
- [x] Sync with SDL2_ttf 2.0.15 headers
- [x] Sync with SDL2_image 2.0.5 headers
- [x] Sync with SDL2_gfx 1.0.4 headers
- [ ] Resolve #145 
- [x] Update README

*Maybe*:
- [x] Fix failing PyPy tests on TravisCI
- [x] Add sdl2dll support
- [ ] Resolve #3 
- [x] Resolve #126 
- [x] Resolve #130 
- [x] Resolve #135 
- [ ] Resolve #139 
- [x] Resolve #132 
- [x] Resolve #136 
- [x] Resolve #75

**Comment by marcusva** [comment]
Except from updating the docs and checking for the latest SDL2 changes, I do not see any major show stopper for a release. Having SDL2 2.0.8 as minimum version dependency also should be sufficient (1.5 years old now).

Does end of January / beginning of February sound good to you for a planned release or do you have some major things to finish beforehand?

**Comment by a-hurst** [comment]
That sounds good to me! Now that CI is hopefully stable again, it should be a lot easier to do updates / add tests for the new SDL2 functions introduced since last release. How do you feel about the sdl2dll proposal, are you on board with adding official support (i.e. not adding it as a dependency, but adding a try/except block that will load it if installed)?

**Comment by marcusva** [comment]
Sounds good to me, as long as we explicitly notify the developer about the usage of the sdl2dll package. Also, sdl2dll should only use official upstream versions of the libraries instead of customized ones (where applicable), so that bug reports can be assigned properly without the need to ponder if it may be related to the custom version of the library.

**Comment by a-hurst** [comment]
Yep, that's how I have sdl2dll set up to work now: when building the wheels, it pulls the official libsdl.org binaries for Windows & macOS for every library except SDL2_gfx (which doesn't have any official builds), where it's using builds from [a CI-based buildbot I put together](https://github.com/a-hurst/sdl2gfx-builds). I'll amend the pull request to add an informative warning when pysdl2 is using it.

**Comment by marcusva** [comment]
Excellent. I try to aim to get everything prepared and done until the 9th or 16th (more likely) of February for the 0.9.7 release.

**Comment by marcusva** [comment]
Done, the new release is out.

**Comment by a-hurst** [comment]
Awesome, thanks so much!
