### ISSUE TITLE
pysdl2 is completely broken on current PyPy & PyPy 3

### ISSUE THREAD

**Issue by a-hurst** [marcusva/py-sdl2#152]
Now that Travis CI has been updated and fixed, we can see that tests on the PyPy interpreters are failing. [Here's the latest PyPy 2 log](https://travis-ci.org/marcusva/py-sdl2/jobs/635553625), but the errors for PyPy 3 are the same. There are only 4 failures, but they're on pretty fundamental things: SDL_Renderer(), SDL_Texture(), SDL_Window(), and TTF_Font() are all broken with the same error:

```
self = <sdl2.test.render_test.SDLRenderTest testMethod=test_SDL_Renderer>

    def test_SDL_Renderer(self):
>       val = render.SDL_Renderer()

self       = <sdl2.test.render_test.SDLRenderTest testMethod=test_SDL_Renderer>

sdl2/test/render_test.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/python/pypy2.7-7.1.1/lib_pypy/_ctypes/structure.py:269: in __init__
    type(self)._make_final()
/opt/python/pypy2.7-7.1.1/lib_pypy/_ctypes/structure.py:208: in _make_final
    self._fields_ = []  # As a side-effet, this also sets the ffishape.
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <class 'sdl2.render.SDL_Renderer'>, name = '_fields_', value = []

    def struct_setattr(self, name, value):
        if name == '_fields_':
            if self.__dict__.get('_fields_', None) is not None:
                raise AttributeError("_fields_ is final")
            if self in [f[1] for f in value]:
                raise AttributeError("Structure or union cannot contain itself")
            if self._ffiargtype is not None:
                raise NotImplementedError("Too late to set _fields_: we already "
                            "said to libffi that the structure type %s is opaque"
>                           % (self,))
E               NotImplementedError: Too late to set _fields_: we already said to
libffi that the structure type <class 'sdl2.render.SDL_Renderer'> is opaque
```

I managed to track down the source of the error by finding the PyPy file with the error message and looking at the Git blame, it seems to be this patch here from 2 years back: https://bitbucket.org/pypy/pypy/issues/2813/seems-bug-in-ctypes

Basically, it looks like they changed the interpreter to cache ctypes structures when they're defined and not allow changes to their fields after that point. This is a problem for the aforementioned classes because they're all defined like this:

```python
class TTF_Font(Structure):
    pass
```

i.e. we're pleading ignorance of the actual structure and letting Python fill in the blanks. Looking at the SDL2 docs, this seems hard to avoid because these are all undocumented internal structures that can change from version to version. Thus, in order to fix, we really only have 2 options:

1. Specify the structures fully and try and keep on top of any version-to-version changes, or
2. Figure out a way for PyPy to allow for the kind of behavior we're asking of it here.

Alternatively, we may have to drop PyPy support if there's no good fix. I'll file a report with PyPy and see what the maintainers suggest.

**Comment by marcusva** [comment]
Specifying the structures can quickly become a huge pain due to ABI compatibility issues, at least from my experience back from the pygame project. ctypes seems to be heavily neglected every since I experimented with it on PyPy.
The usual recommendation that I saw in such cases was to switch to cffi. Personally, I'm not that fond of using cffi as long as it is not a standard subset of Python.

**Comment by a-hurst** [comment]
Agreed about cffi. Even if porting over all the headers from ctypes to cffi was trivial, it would still either require end-users to have a functioning compiler (absolutely awful on Windows, where you need to install the full Visual Studio just to build Python C extensions) or would require us to provide up-to-date binary wheels for all major OSes and Python versions, which would also be a pain (though cibuildwheel would make it less of a headache).

**Comment by a-hurst** [comment]
Fixed in latest commit! All it took was switching out Strucutre for c_void_p as class to subclass for the opaque structures in question, and a little voodoo to avoid a weird segfault during the sprite tests in PyPy3 (didn't seem to like evaluating `if self.texture:`, but is apparently fine with `if self.texture != None`).
