### ISSUE TITLE
How come my game is running super slow?

### ISSUE THREAD

**Issue by fabtjar** [marcusva/py-sdl2#161]
Am I doing something stupid with how I'm rendering the images?

https://github.com/fabianjarrett/py-platformer-game

I think I've go my references done up really inefficient!

Not sure where else I could have asked this. Point me in the right direction if it should be asked somewhere else.

**Comment by marcusva** [comment]
You are doing a full update (including redrawing everything, within your Game's run() method.
Imagine your mouse moving over the display, which may issue hundreds of mouse movement events within 100 ms. After you dealt with a single of those events via SDL_PollEvent() in https://github.com/fabianjarrett/py-platformer-game/blob/cf9e6f3101d33ee7f7dbd35337555b4c26bb7703/core/game.py#L31, you are redrawing the screen. Then, after you handled the next one, you are redrawing the screen. And so on, and so forth. This is rather inefficient and causes huge delays.

Update the screen either in fixed intervals (e.g based on the stepping deltas of your loop, rather simple) or only, if there is a need (more complex):

```python
while running:
     while sdl2.SDL_PollEvent(ctypes.byref(event)) != 0:
          # do your event handling
     game.update()
     # optional: SDL_Delay(some_sensible_delta_in_ms) to reduce the CPU load 
```

You can find some simple examples in the py-sdl2 examples folder. You can also take a look at other py-sdl2 projects or even pygame-based ones (if you do not mind the API differences) as a starting point for implementing a solid event and update loop.

**Comment by fabianjarrett** [comment]
@marcusva Thanks very much for the feedback! 👍
