### ISSUE TITLE
sdl2.ext.draw.fill: area should be able to be SDL_Rect

### ISSUE THREAD

**Issue by iKarith** [marcusva/py-sdl2#169]
If I set area to be a tuple, I get the correct fill. If I set it to SDL_Rect with the same contents, what I get is the entire surface filled.

Using 0.9.4 on Linux Mint 20 (Ubuntu Focal base). I'll fix my code—I intended this to be temporary code anyway.

**Comment by a-hurst** [comment]
Hey, sorry, for some reason I haven't been getting notifications for new issues! I'll make some time to tackle your issues and your PR soon, though that might not be until late this month as I have other projects that need work. Thanks for helping make this package better!

**Comment by a-hurst** [comment]
This seems like an easy fix, I'll add this after the 2.0.14 updates are done!

**Comment by a-hurst** [comment]
@iKarith Sorry for the delay, finally fixed as of this commit! https://github.com/marcusva/py-sdl2/commit/32b81f4a909ebd339058ddc438e03100b832f807
