### ISSUE TITLE
__file__ not defined in Tutorial's helloworld.html

### ISSUE THREAD

**Issue by rrpegasus** [marcusva/py-sdl2#174]
(Python 3.9.2 - pySDL2 0.9.7 - Windows 10)
RESOURCES = sdl2.ext.Resources(\_\_file\_\_, "resources")
is wrong. It should be
RESOURCES = sdl2.ext.Resources(sdl2.\_\_file\_\_,os.path.join("examples","resources"))
instead.

**Comment by a-hurst** [comment]
@rrpegasus Good catch, thanks for this! I've been quite busy over the past few months, but will include this fix with the rest of the 2.0.14 updates when I finish them.

**Comment by a-hurst** [comment]
Fixed in the latest commit!
