### ISSUE TITLE
ImportError: found [the library], but it's not usable for the library SDL2_mixer

### ISSUE THREAD

**Issue by mwerezak** [marcusva/py-sdl2#189]
**What doesn't work?**
```ImportError: found ['.../venv/lib/python3.9/site-packages/sdl2dll/dll/libSDL2_mixer-2.0.so'], but it's not usable for the library SDL2_mixer```

Okay, why is it not usable?

**How To Reproduce**
Any code that reproduces the bug, e.g.:
```
pip install PySDL2
pip install pysdl2-dll
```

**Platform (if relevant):**
 - OS: Debian 10
 - Python Version: 3.9.6
 - SDL2 Version: 0.9.7
 - Using pysdl2-dll: yes

**Additional context**
Trying to get https://github.com/sudasana/armcom2 running. Can't find any leads on what to do here.

**Comment by a-hurst** [comment]
@mwerezak If you open a fresh interactive Python session and run `import sdl2` and then `from sdl2 import mixer`, do you get the same error? I've tested pysdl2 and pysdl2-dll on a Debian 10 machine and it works fine with simple demos, though using Python 3.7 so maybe something about how it loads libraries has changed in newer versions (currently installing 3.9 via pyenv so I can test if that breaks it, though).

Apologies for the "not usable" error being a bit vague: it just means Python's ctypes module had some unknown error loading the library, so it's hard to be more specific (I should probably be clearer about it being a ctypes issue though).

**Comment by mwerezak** [comment]
> EDIT: Just fresh-installed Python 3.9.6 on Debian 10 and installed pysdl2 + pysdl2-dll, no errors on running import sdl2; from sdl2 import sdlmixer. I also tried installing the game you linked, but gave up after spending ~20 minutes trying to figure out how to install libtcod.

I just tried it on my machine as well. No issues with `import sdl2.sdlmixer as mixer` other than `UserWarning: Using SDL2 binaries from pysdl2-dll 2.0.14`. Very strange. 

On Debian 10 you can install `libtcod-dev` with APT and then copy or symlink all of the libtcod.so* to the `libtcodpy_local` folder in the armcom2. In any case other than the message being cryptic the library does import in a fresh interpreter so the issue could be on the armcom2 end of things.

**Comment by mwerezak** [comment]
Okay, so to debug this I ran the following in a fresh interpreter. Using venv, so `site-packages` contains nothing but pysdl2 + pysdl2-dll. This is just everything in `armcom2.py` up to the sdlmixer import:
```
import os, sys
import libtcodpy_local as libtcod
from configparser import ConfigParser
from random import choice, shuffle, sample
from math import floor, cos, sin, sqrt, degrees, atan2, ceil
import xp_loader, gzip
import json
import time
from datetime import datetime, timedelta
from textwrap import wrap
import shelve
import sdl2.sdlmixer as mixer
```

The error occurs as before. So next I start eliminating import statements and narrowed it down to the following:
```
import xp_loader
import sdl2.sdlmixer as mixer
```

So without digging into `xp_loader` that will reproduce the issue. Sorry for not including this in the initial report but it was pretty late at night.

**Comment by a-hurst** [comment]
> > EDIT: Just fresh-installed Python 3.9.6 on Debian 10 and installed pysdl2 + pysdl2-dll, no errors on running import sdl2; from sdl2 import sdlmixer. I also tried installing the game you linked, but gave up after spending ~20 minutes trying to figure out how to install libtcod.
> 
> I just tried it on my machine as well. No issues with `import sdl2.sdlmixer as mixer` other than `UserWarning: Using SDL2 binaries from pysdl2-dll 2.0.14`. Very strange.
> 
> On Debian 10 you can install `libtcod-dev` with APT and then copy or symlink all of the libtcod.so* to the `libtcodpy_local` folder in the armcom2. The library does import in a fresh interpreter though so it may be something going on with armcom2.

Have you tried uninstalling pysdl2-dll and letting pysdl2 use the system's SDL2 binaries? From the looks of it, libtcod is built around SDL2, so the error might be caused by libtcod linking one version of SDL2 and pysdl2-dll linking a different one.

If you'd like to keep pysdl2-dll around for other projects, you can also just set `PYSDL2_DLL_PATH=system` in your environment to tell pysdl2 to ignore the pysdl2-dll binaries.

**Comment by mwerezak** [comment]
I tried setting `PYSDL2_DLL_PATH=system` but then SDL2_mixer won't import...
```
ImportError: could not find any library for SDL2_mixer (PYSDL2_DLL_PATH: system)
```

**Comment by a-hurst** [comment]
If you run `apt-get install libsdl2-mixer-2.0-0`, does it work then? I'm guessing libtcod only requires SDL2 itself and not any of the submodules, but if its SDL2 is loaded first, pysdl2-dll's `SDL_mixer` runs into trouble because it's expecting to be linked to pysdl2-dll's SDL2 binary.

**Comment by mwerezak** [comment]
Aha that was it. I didn't realize mixer wasn't included in libsdl2.

**Comment by a-hurst** [comment]
Great, glad you got it working!
