### ISSUE TITLE
Missing code in an issue

### ISSUE THREAD

**Issue by schneems** [marcusva/py-sdl2#192]
I commented on [this gist](https://gist.github.com/ChickenProp/3194723#gistcomment-2023091) that I had written code in and left it on an issue in this repo on bitbucket https://bitbucket.org/marcusva/py-sdl2/issues/101/liangbarsky-incorrect. It looks like you've moved from bitbucket and the issues didn't translate over so the code seems to be lost.

Is it possible to revive that code or issue somehow? Maybe unarchive that repo and grab it?

**Comment by a-hurst** [comment]
Hi @schneems, is this the code/issue you were referring to? https://github.com/marcusva/py-sdl2/issues/101

I'm not the original PySDL2 maintainer, but I recently did a cleanup of that module which I think fixes the problem you described in that issue, so please met me know if there are any more liang-barsky issues with the latest PyPI release!
