### ISSUE TITLE
[regression] SDL_WINDOW_INPUT_GRABBED is no longer exported as of 0.9.9

### ISSUE THREAD

**Issue by rollcat** [marcusva/py-sdl2#195]
**What doesn't work?**

Importing the constant `SDL_WINDOW_INPUT_GRABBED` is no longer possible as of 0.9.9; it was possible in 0.9.8.

**How To Reproduce**

```
from sdl2 import SDL_WINDOW_INPUT_GRABBED
```

My test environment:

```
docker run -ti --rm alpine:latest
apk add py3-pip ipython sdl2
pip install pysdl2==0.9.9  # or 0.9.8, to verify that it's still working
ipython
import sdl2
from sdl2 import SDL_WINDOW_INPUT_GRABBED
```

**Tested platforms:**
 - OS: 1. Ubuntu 18.04 (arm64); 2. Alpine latest (x86-64)
 - Python Version: 1. 3.6; 2. 3.9
 - SDL2 Version: 1. 2.0.8+dfsg1-1ubuntu1.18.04.4; 2. 2.0.14-r1
 - Using pysdl2-dll: Nope

**Comment by a-hurst** [comment]
@rollcat Sorry for the delay, this should be fixed as of https://github.com/marcusva/py-sdl2/commit/b4f90ca7e59c6d5ccefed0c063286fca35279208 !
