### ISSUE TITLE
SDL_SetHint wrong type

### ISSUE THREAD

**Issue by keenfoong** [marcusva/py-sdl2#198]
**What doesn't work?**
Firstly apologies if I'm doing something wrong here, I'm still new to SDL. I'm attempting to run the SDL_SetHint function as follows:

`sdl2.SDL_SetHint(sdl2.SDL_HINT_RENDER_SCALE_QUALITY, "2")`
Basing it off the documentation here:
https://wiki.libsdl.org/SDL_SetHint

However I get this error:
```
File "D:\Code\pysdl2\examples\particles.py", line 201, in run
    sdl2.SDL_SetHint(sdl2.SDL_HINT_RENDER_SCALE_QUALITY, "2")
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Platform (if relevant):**
 - OS: Windows 10 64-bit
 - Python Version: 3.9.6
 - SDL2 Version: 2.0.16
 - Using pysdl2-dll: yes

What am I doing wrong here?

**Comment by a-hurst** [comment]
Hi @keenfoong, I think the issue is that the second argument should be `bytes` type instead of `str`, since SDL2 generally expects UTF-8 encoded byte strings for string arguments.

Try the same code again with `sdl2.SDL_SetHint(sdl2.SDL_HINT_RENDER_SCALE_QUALITY, b"2")` and see if that works!

**Comment by keenfoong** [comment]
That worked thanks!
