### ISSUE TITLE
 SDL_MouseWheelEvent direction field missing

### ISSUE THREAD

**Issue by esoma** [marcusva/py-sdl2#217]
Seems like #197 accidentally removed the direction field from `SDL_MouseWheelEvent` (https://github.com/libsdl-org/SDL/blob/120c76c84bbce4c1bfed4e9eb74e10678bd83120/include/SDL_events.h#L303)

**Comment by a-hurst** [comment]
@esoma Oof, can't believe I missed that one. Thanks for reporting it, I'll make sure it's fixed in the next release!

**Comment by a-hurst** [comment]
Okay, fixed in https://github.com/marcusva/py-sdl2/commit/e9ac280dd21b54e65753f6911a2800d7b984d100. Thanks for catching this!
