### ISSUE TITLE
SDL_RenderSetVSync not exported

### ISSUE THREAD

**Issue by hemesath** [marcusva/py-sdl2#219]
**What doesn't work?**
When trying to import `SDL_RenderSetVSync` from `sdl2`, an `ImportError` is raised.

**How To Reproduce**
```python
from sdl2 import SDL_RenderSetVSync
```

**The Reason**
The function is defined in `sdl2/render.py` but it is not exported. I.e. it's missing from `render`'s `__all__` list.
Thus, the function can only be imported directly from `sdl2.render`
```python
from sdl2.render import SDL_RenderSetVsync
```

Thanks in advance!

**Comment by a-hurst** [comment]
@hemesath Whoops, nice catch! Thanks for reporting this, I'll make sure it's fixed in the next release.

**Comment by a-hurst** [comment]
Fixed in https://github.com/marcusva/py-sdl2/commit/c6c34063fbd541f502fd4c45cd127236fa0a4292. I also updated the unit tests suite to be better at catching namespace bugs like this. Thanks again!

**Comment by hemesath** [comment]
Great idea to add a test for that.
Have a nice weekend! :D
