### ISSUE TITLE
Description for wrapping lines is missing bg color problem

### ISSUE THREAD

**Issue by marcusva** [marcusva/py-sdl2#60]
Originally reported by: **Moini (Bitbucket: [Moini](https://bitbucket.org/Moini), GitHub: [Moini](https://github.com/Moini))**

----------------------------------------

Hi again ;-)
I'm happy I finally found how to render fonts, this should definitely be documented somewhere with all necessary steps.

On rendering wrapped text I found an inconsistency:

When you choose to tell pySDL2 a max width for the wrapped text so it can be wrapped, pySDL2 forgets about the background color.

This is, because the called function TTF_RenderUTF8_Blended_Wrapped, which is called 'if width' doesn't take background colors, only the font color. (files: font.py and SDL_ttf.h).

I think there are two possible solutions:

a) document this behaviour

b) build a rectangle of the desired background color behind the wrapped text

----------------------------------------
- Bitbucket: https://bitbucket.org/marcusva/py-sdl2/issue/60

**Comment by zmarvel** [comment]
I'm interested in working on this ticket. @marcusva, do you have a preferred fix, i.e. do you prefer documenting the behavior, rendering a rectangle behind the text, or an alternative solution?

**Comment by a-hurst** [comment]
This should be fixed as of PR #134. Also, it's probably worth pointing out that a proper [TTF_RenderUTF8_Shaded_Wrapped](https://hg.libsdl.org/SDL_ttf/rev/9f46efc0fde2) function was implemented in SDL2_ttf earlier this year, which will probably be a cleaner solution going forward.
